import {
  SiJavascript,
  SiReact,
  SiTypescript,
  SiHtml5,
  SiCss3,
  SiGit,
  SiRedux,
  SiStyledcomponents,
  SiMui,
  SiExpress,
  SiMysql,
  SiMongodb,
  SiNodedotjs,
  SiTailwindcss,
  SiDotnet,
  SiGnometerminal,
} from 'react-icons/si';

export const icons = [
  { icon: SiGnometerminal },
  { icon: SiJavascript },
  { icon: SiTypescript },
  { icon: SiReact },
  { icon: SiRedux },
  { icon: SiGit },
  { icon: SiHtml5 },
  { icon: SiCss3 },
  { icon: SiStyledcomponents },
  { icon: SiMui },
  { icon: SiTailwindcss },
  { icon: SiExpress },
  { icon: SiMysql },
  { icon: SiMongodb },
  { icon: SiNodedotjs },
  { icon: SiDotnet },
];
