import {
  SiJavascript,
  SiReact,
  SiTypescript,
  SiHtml5,
  SiCss3,
  SiGit,
  SiRedux,
  SiStyledcomponents,
  SiMui,
  SiExpress,
  SiMysql,
  SiMongodb,
  SiNodedotjs,
  SiTailwindcss,
  SiDotnet,
  SiGnometerminal,
} from 'react-icons/si';

export const iconList = [
  { component: SiGnometerminal },
  { component: SiJavascript },
  { component: SiTypescript },
  { component: SiReact },
  { component: SiRedux },
  { component: SiGit },
  { component: SiHtml5 },
  { component: SiCss3 },
  { component: SiStyledcomponents },
  { component: SiMui },
  { component: SiTailwindcss },
  { component: SiExpress },
  { component: SiMysql },
  { component: SiMongodb },
  { component: SiNodedotjs },
  { component: SiDotnet },
];
